global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]

    - job_name: "redpanda"
      static_configs:
          - targets: ["redpanda:9644"]

    - job_name: "postgres"
      static_configs:
          - targets: ["postgres-exporter:9187"]
